# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    #Waiting for next vagrant version
    #config.vm.box_url = "http://storage.core-os.net/coreos/amd64-generic/dev-channel/coreo"
    #config.vm.box = "coreos"
    #
    config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210-nocm.box"
    config.vm.box = "ubuntu-server-12042-x64-vbox4210-nocm.box"

    config.vm.provider :virtualbox do |vb|
    vb.customize [
        "modifyvm", :id,
        "--memory", "256",
        "--cpus", "1"]
    end

    config.vm.define :b1 do |b1|
        b1.vm.hostname = "b1"
        b1.vm.network :private_network, ip: "192.168.22.32"
        b1.vm.provision "shell", path: "provision.sh"
    end

    config.vm.define :b2 do |b2|
        b2.vm.hostname = "b2"
        b2.vm.network :private_network, ip: "192.168.22.33"
        b2.vm.provision "shell", path: "provision.sh"
    end

    config.vm.define :b3 do |b3|
        b3.vm.hostname = "b3"
        b3.vm.network :private_network, ip: "192.168.22.34"
        b3.vm.provision "shell", path: "provision.sh"
    end

    config.vm.define :b4 do |b4|
        b4.vm.hostname = "b4"
        b4.vm.network :private_network, ip: "192.168.22.35"
        b4.vm.provision "shell", path: "provision.sh"
    end

end
