# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    #Waiting for next vagrant version
    #config.vm.box_url = "http://storage.core-os.net/coreos/amd64-generic/dev-channel/coreo"
    #config.vm.box = "coreos"
    #
    config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210-nocm.box"
    config.vm.box = "ubuntu-server-12042-x64-vbox4210-nocm.box"

    config.vm.provision :shell, :inline => "
    sh -c \"curl https://get.docker.io/gpg | apt-key add -\"
    sh -c \"echo deb https://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list\"
    apt-get update
    apt-get install lxc-docker -y
    sed -i 's/docker -d$/docker -d -H=tcp:\\/\\/0.0.0.0/g' /etc/init/docker.conf
    stop docker
    initctl reload docker
    start docker
    "

    config.vm.define :b1 do |b1|
        b1.vm.hostname = "b1"
        b1.vm.network :private_network, ip: "192.168.22.32"
    end

    config.vm.define :b2 do |b2|
        b2.vm.hostname = "b2"
        b2.vm.network :private_network, ip: "192.168.22.33"
    end

    config.vm.define :b3 do |b3|
        b3.vm.hostname = "b3"
        b3.vm.network :private_network, ip: "192.168.22.34"
    end

    config.vm.define :b4 do |b4|
        b4.vm.hostname = "b4"
        b4.vm.network :private_network, ip: "192.168.22.35"
    end

end
